### ISSUE TITLE
Any way to buy the board outside China? 

### ISSUE THREAD

**Issue by diyprojectz** [hhuysqt/esp32s3-keyboard#6]
Hello,

Is there any way I can order it? I am outside China.

Thank you

你好，

有什么办法可以订购吗？ 我在中国境外。

谢谢

**Comment by hhuysqt** [comment]
Hi, I've updated the kicad PCB project along with gerber files, so that you can make the PCB on your own. Sorry but I'm no longer selling the board since it is just a hobby project :-D

**Comment by antonba** [comment]
What is a good company to order the board from that can also solder all components on it (e.g. ESP32, FPC connectors, USB port)? Which company did you use?
